####################################################################################
# SETTINGS FILE (in the yaml format: leave a spece after the ":" (e.g. name: value). Put values that start with "!" in quotation marks. Allows pythonic scientific notation and simple math operations listed in settings.py)
####################################################################################
 
####################################################################################
# important settings:
####################################################################################


####################################################################################
# less important settings:
####################################################################################




####################################################################################
####################################################################################
# examples & how to import variables in python:
####################################################################################

# --- in settings.yaml (=here) ---

# example 1: a string
# example 2: "a string"
# example 3: 1
# example 4: 1.2
# example 5: true
# example 6: True
# example 7:
# example 8: 1e3
# example 9: 1.4e2/5e2
# example 10: 1+5e1
# example 11: 2*1e4^3e0
# example 12: 5/1e4^3e0

# --- in code.py: ---
# import settings

# s["example 1"] == "a string"
# s["example 2"] == "a string"
# s["example 3"] == 1
# s["example 4"] == 1.2
# s["example 5"] == True
# s["example 6"] == True
# s["example 7"] == None
# s["example 8"] == 1000.0

####################################################################
####################################################################



